name: Report a bug
description: |
  You found a bug in the library causing your application to crash or
  throw an exception, a feature is buggy, unexpected behavior or something looks wrong.
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the library!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
      - label: I have searched the [existing issues](https://github.com/freshtechtips/ktor-server-firebase-app-check/issues)
        required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please tell us exactly how to reproduce the problem you are running into.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected results
      description: Please tell us what is expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual results
      description: Please tell us what is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code sample
      description: |
        Please create a minimal reproducible sample that shows the problem
        and attach it below between the lines with the backticks.

        To create it, use the [Ktor project generator](https://start.ktor.io/)

        Note: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload your code sample.
      value: |
        <details><summary>Code sample</summary>

        ```kotlin
        [Paste your code here]
        ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or Video
      description: |
        Upload any screenshots or video of the bug if applicable.
      value: |
        <details>
        <summary>Screenshots / Video demonstration</summary>

        [Upload media here]

        </details>
  - type: textarea
    attributes:
      label: Logs
      description: |
        Include the full logs of the commands you are running between the lines
        with the backticks below.

        If the logs are too large to be uploaded to GitHub, you may upload
        them as a `txt` file or use online tools like https://pastebin.com to
        share it.

        Note: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload logs.
      value: |
        <details><summary>Logs</summary>

        ```console
        [Paste your logs here]
        ```

        </details>
  - type: textarea
    attributes:
      label: Gradle version output (optional)
      description: |
        Please provide the full output of running `gradle --version`
        if the issue is related on how the library use Gradle
      value: |
        <details><summary>Doctor output</summary>

        ```console
        [Paste your output here]
        ```

        </details>