name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      # - name: Validate Gradle Wrapper
      #   uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          # For more info: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#incompatibility-with-other-caching-mechanisms
          # cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
          cache-disabled: false

      - name: Make sure the `./gradlew` is executable
        run: chmod +x ./gradlew
        working-directory: ./server

      - name: Build & Test with Gradle
        run: ./gradlew build --stacktrace
        working-directory: ./server
